#define SECRET_SSID "wifissidHere"
#define SECRET_PASS "wifipassHere"
#define SECRET_BROKER "Raspi ip Here"
#define SECRET_SENSORTOPIC "sensors/sensoridHere/readings"
#define SECRET_SERVER "osuscc-testing.azurewebsites.net"
#define SECRET_HOMEURL "/api/homes/homeidHere/"
#define SECRET_TOKEN "Bearer 123456"
#define SECRET_METHOD "http"
#define SECRET_INTERVAL "Interval in milliseconds"
